site_name: Asterisk Engine Documentation
site_url: https://ametrine.cc/asteriskengine

nav:
  - Home: index.md
  - About: about.md
  - Installation: getting_started.md
  - Documentation:
    - Creating a window: creating_a_window.md
    - Window settings: window_settings.md
    
    - Drawing Shapes and Text:
      - Drawing your first text: drawing_your_first_text.md
      - Drawing your first shape: drawing_your_first_shape.md
    
    - Sprites:
      - Drawing your first sprite: drawing_your_first_sprite.md
      - Drawing your first animated sprite: drawing_your_first_animated_sprite.md

    - Input Handling:
      - Handling keyboard input: handling_keyboard_input.md
      - Handling mouse input: handling_mouse_input.md
    
    - Managing Audio:
      - Playing and Stopping audio: playing_audio.md
      - Controlling audio: controlling_audio.md
    
  - Cheatsheet: cheatsheet.md
  - Contribution: contribution.md
  - License: license.md

theme:
  name: material
  favicon: 'assets/favicon.ico'
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.footer